server:
  port: 9527

# eureka客户端配置
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eurekaserver7001.com:7001/eureka/


# zuul配置
zuul:
  routes:
    dept-provider.serviceId: microservicecloud-dept
    dept-provider.path: /mydept/**









